// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZEdMu0Sv3XRofW4vfaeRF--nINy1e0o',
    appId: '1:861344555964:web:cb74f315f949251c7101b9',
    messagingSenderId: '861344555964',
    projectId: 'detail-crud',
    authDomain: 'detail-crud.firebaseapp.com',
    databaseURL: 'https://detail-crud-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'detail-crud.appspot.com',
    measurementId: 'G-TSTDWZQFRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATYfYj_Dp1pimiBZCd_g4XrZ_3vJRR-dU',
    appId: '1:861344555964:android:39134e67dfaf824f7101b9',
    messagingSenderId: '861344555964',
    projectId: 'detail-crud',
    databaseURL: 'https://detail-crud-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'detail-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQeIVss8RFVczXDWprMR1FPubpbgEkGic',
    appId: '1:861344555964:ios:e4ae377880139b057101b9',
    messagingSenderId: '861344555964',
    projectId: 'detail-crud',
    databaseURL: 'https://detail-crud-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'detail-crud.appspot.com',
    iosClientId: '861344555964-efqm6i705atafnkiviukpjfsqlk0acvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectOrangeIsh',
  );
}
